# Site settings
title: veb co nz
email: e-male@veb.co.nz.dev
description: > # this means to ignore newlines until "baseurl:"
  Something in meta... so meta
baseurl: ""
url: "http://veb.co.nz" # the base hostname & protocol for your site
twitter_username: actualbrain
github_username:  actualbrain

# Build settings
markdown: kramdown

encoding: utf-8

sass:
  sass_dir: _sass
  style: :nested

gems: [font-awesome-sass]

include: [".htpasswd", ".htaccess"]